package com.bridge.calculator.core.elbow

/**
 * 68种桥架弯头注册表
 */
object ElbowRegistry {
    private val _elbows = mutableListOf<ElbowSpec>()
    val elbows: List<ElbowSpec> get() = _elbows
    
    init { registerAllElbows() }
    
    private fun registerAllElbows() {
        // 1. 上下爬坡类 (6种)
        _elbows.add(ElbowSpec(1, "左爬坡弯头", ElbowCategory.UP_DOWN_RAMP, "左侧爬坡弯头", listOf(DefaultParams.width, DefaultParams.height, DefaultParams.angle, DefaultParams.distance), listOf("底边X", "斜边L", "爬坡高度", "切口宽", "折弯位置"), "X = b × tan(α/2)", { FormulaEngine.calcRamp(it) }, ModelType.RAMP))
        _elbows.add(ElbowSpec(2, "右爬坡弯头", ElbowCategory.UP_DOWN_RAMP, "右侧爬坡弯头", listOf(DefaultParams.width, DefaultParams.height, DefaultParams.angle, DefaultParams.distance), listOf("底边X", "斜边L", "爬坡高度", "切口宽", "折弯位置"), "X = b × tan(α/2)", { FormulaEngine.calcRamp(it) }, ModelType.RAMP))
        _elbows.add(ElbowSpec(3, "左下坡弯头", ElbowCategory.UP_DOWN_RAMP, "左侧下坡弯头", listOf(DefaultParams.width, DefaultParams.height, DefaultParams.angle, DefaultParams.distance), listOf("底边X", "斜边L", "下降高度", "切口宽", "折弯位置"), "X = b × tan(α/2)", { FormulaEngine.calcRamp(it) }, ModelType.RAMP))
        _elbows.add(ElbowSpec(4, "右下坡弯头", ElbowCategory.UP_DOWN_RAMP, "右侧下坡弯头", listOf(DefaultParams.width, DefaultParams.height, DefaultParams.angle, DefaultParams.distance), listOf("底边X", "斜边L", "下降高度", "切口宽", "折弯位置"), "X = b × tan(α/2)", { FormulaEngine.calcRamp(it) }, ModelType.RAMP))
        _elbows.add(ElbowSpec(5, "垂直上弯头", ElbowCategory.UP_DOWN_RAMP, "垂直向上转弯", listOf(DefaultParams.width, DefaultParams.height, DefaultParams.heightOffset), listOf("斜边L", "垂直高度", "切口宽"), "L = h", { val h = it.heightOffset; listOf(CalcResult("斜边L", h, "mm"), CalcResult("垂直高度", h, "mm"), CalcResult("切口宽", h * 0.3, "mm")) }, ModelType.RAMP))
        _elbows.add(ElbowSpec(6, "垂直下弯头", ElbowCategory.UP_DOWN_RAMP, "垂直向下转弯", listOf(DefaultParams.width, DefaultParams.height, DefaultParams.heightOffset), listOf("斜边L", "垂直高度", "切口宽"), "L = h", { val h = it.heightOffset; listOf(CalcResult("斜边L", h, "mm"), CalcResult("垂直高度", h, "mm"), CalcResult("切口宽", h * 0.3, "mm")) }, ModelType.RAMP))
        
        // 2. 水平转向类 (3种)
        _elbows.add(ElbowSpec(7, "水平左弯30°", ElbowCategory.HORIZONTAL_TURN, "水平面内左转30度", listOf(DefaultParams.width, DefaultParams.height, ParamDef("角度", "angle", "°", 30.0, 1.0, 179.0), DefaultParams.distance), listOf("底边X", "弧长L", "切口宽"), "X = b × 0.536", { FormulaEngine.calcHorizontal(it.copy(angle = 30.0)) }, ModelType.HORIZONTAL))
        _elbows.add(ElbowSpec(8, "水平右弯30°", ElbowCategory.HORIZONTAL_TURN, "水平面内右转30度", listOf(DefaultParams.width, DefaultParams.height, ParamDef("角度", "angle", "°", 30.0, 1.0, 179.0), DefaultParams.distance), listOf("底边X", "弧长L", "切口宽"), "X = b × 0.536", { FormulaEngine.calcHorizontal(it.copy(angle = 30.0)) }, ModelType.HORIZONTAL))
        _elbows.add(ElbowSpec(9, "水平90°弯头", ElbowCategory.HORIZONTAL_TURN, "水平面内转角90度", listOf(DefaultParams.width, DefaultParams.height, DefaultParams.distance), listOf("底边X", "斜边L", "切口宽", "弯曲半径"), "90° = 两个45°组合", { FormulaEngine.calc90Degree(it) }, ModelType.HORIZONTAL))
        
        // 3. 组合翻弯类 (10种)
        _elbows.add(ElbowSpec(10, "45+45°组合弯", ElbowCategory.COMPOSITE_FLIP, "两个45度弯头组合", listOf(DefaultParams.width, DefaultParams.height, ParamDef("第一段距离", "distance1", "mm", 150.0, 50.0, 1000.0), ParamDef("第二段距离", "distance2", "mm", 150.0, 50.0, 1000.0)), listOf("第一段底边", "第一段斜边", "第二段底边", "第二段斜边", "总高度"), "各段独立计算", { FormulaEngine.calcComposite(it.copy(angle1 = 45.0, angle2 = 45.0)) }, ModelType.COMPOSITE))
        _elbows.add(ElbowSpec(11, "30+30°组合弯", ElbowCategory.COMPOSITE_FLIP, "两个30度弯头组合", listOf(DefaultParams.width, DefaultParams.height, ParamDef("第一段距离", "distance1", "mm", 200.0, 50.0, 1000.0), ParamDef("第二段距离", "distance2", "mm", 200.0, 50.0, 1000.0)), listOf("第一段底边", "第一段斜边", "第二段底边", "第二段斜边", "总高度"), "各段独立计算", { FormulaEngine.calcComposite(it.copy(angle1 = 30.0, angle2 = 30.0)) }, ModelType.COMPOSITE))
        _elbows.add(ElbowSpec(12, "45+30°组合弯", ElbowCategory.COMPOSITE_FLIP, "45度和30度弯头组合", listOf(DefaultParams.width, DefaultParams.height, ParamDef("第一段距离", "distance1", "mm", 150.0, 50.0, 1000.0), ParamDef("第二段距离", "distance2", "mm", 200.0, 50.0, 1000.0)), listOf("第一段底边", "第一段斜边", "第二段底边", "第二段斜边", "总高度"), "45° + 30° = 75°", { FormulaEngine.calcComposite(it.copy(angle1 = 45.0, angle2 = 30.0)) }, ModelType.COMPOSITE))
        _elbows.add(ElbowSpec(13, "水平之字弯", ElbowCategory.COMPOSITE_FLIP, "水平方向来回弯曲", listOf(DefaultParams.width, DefaultParams.height, DefaultParams.distance, DefaultParams.layers), listOf("每步底边", "总宽度", "切口位置"), "X = (b/n) × tan(α/2)", { val z = FormulaEngine.calcZigzag(it.distance, it.angle, it.layers); z.mapIndexed { i, x -> CalcResult("第${i+1}步底边", x, "mm") } + CalcResult("总宽度", it.distance, "mm") }, ModelType.COMPOSITE))
        _elbows.add(ElbowSpec(14, "垂直之字弯", ElbowCategory.COMPOSITE_FLIP, "垂直方向来回弯曲", listOf(DefaultParams.width, DefaultParams.height, DefaultParams.distance, DefaultParams.layers), listOf("每步高度", "总高度", "切口位置"), "h = (b/n) × tan(α)", { val z = FormulaEngine.calcZigzag(it.distance, it.angle, it.layers); z.mapIndexed { i, x -> CalcResult("第${i+1}步高度", x, "mm") } + CalcResult("总高度", z.last(), "mm") }, ModelType.COMPOSITE))
        _elbows.add(ElbowSpec(15, "左上翻弯", ElbowCategory.COMPOSITE_FLIP, "从下方向左上方翻起", listOf(DefaultParams.width, DefaultParams.height, DefaultParams.angle, DefaultParams.distance, DefaultParams.heightOffset), listOf("底边X", "斜边L", "翻起高度", "切口宽"), "复合计算", { FormulaEngine.calcRamp(it) }, ModelType.COMPOSITE))
        _elbows.add(ElbowSpec(16, "右上翻弯", ElbowCategory.COMPOSITE_FLIP, "从下方向右上方翻起", listOf(DefaultParams.width, DefaultParams.height, DefaultParams.angle, DefaultParams.distance, DefaultParams.heightOffset), listOf("底边X", "斜边L", "翻起高度", "切口宽"), "复合计算", { FormulaEngine.calcRamp(it) }, ModelType.COMPOSITE))
        _elbows.add(ElbowSpec(17, "左下翻弯", ElbowCategory.COMPOSITE_FLIP, "从上方向左下方翻下", listOf(DefaultParams.width, DefaultParams.height, DefaultParams.angle, DefaultParams.distance, DefaultParams.heightOffset), listOf("底边X", "斜边L", "翻下高度", "切口宽"), "复合计算", { FormulaEngine.calcRamp(it) }, ModelType.COMPOSITE))
        _elbows.add(ElbowSpec(18, "右下翻弯", ElbowCategory.COMPOSITE_FLIP, "从上方向右下方翻下", listOf(DefaultParams.width, DefaultParams.height, DefaultParams.angle, DefaultParams.distance, DefaultParams.heightOffset), listOf("底边X", "斜边L", "翻下高度", "切口宽"), "复合计算", { FormulaEngine.calcRamp(it) }, ModelType.COMPOSITE))
        _elbows.add(ElbowSpec(19, "扇形弯头", ElbowCategory.COMPOSITE_FLIP, "多段小角度组合成大角度", listOf(DefaultParams.width, DefaultParams.height, ParamDef("总角度", "angle", "°", 90.0, 30.0, 180.0), ParamDef("分段数", "layers", "", 6.0, 3.0, 12.0)), listOf("每段角度", "每段底边", "总弧长"), "分段计算叠加", { val sa = it.angle / it.layers; val x = FormulaEngine.calcBottomX(it.distance, sa); val l = FormulaEngine.calcHypotenuse(it.distance, sa); listOf(CalcResult("每段角度", sa, "°"), CalcResult("每段底边", x, "mm"), CalcResult("总弧长", l * it.layers, "mm")) }, ModelType.COMPOSITE))
        
        // 4. 特殊造型类 (10种)
        _elbows.add(ElbowSpec(20, "水平弧弯", ElbowCategory.SPECIAL_SHAPE, "圆弧形过渡的水平弯头", listOf(DefaultParams.width, DefaultParams.height, DefaultParams.angle, DefaultParams.distance), listOf("弧半径", "弧长", "切口宽"), "R = b / (2 × sin(α/2))", { val a = it.angle * kotlin.math.PI / 180; val r = it.distance / (2 * kotlin.math.sin(a / 2)); listOf(CalcResult("弧半径", r, "mm"), CalcResult("弧长", r * a, "mm"), CalcResult("切口宽", r * a * 0.3, "mm")) }, ModelType.HORIZONTAL))
        _elbows.add(ElbowSpec(21, "水平扭弯", ElbowCategory.SPECIAL_SHAPE, "扭转方向的特殊弯头", listOf(DefaultParams.width, DefaultParams.height, DefaultParams.angle), listOf("扭转长度", "切口位置"), "L = W × tan(α/2)", { val l = it.width * kotlin.math.tan(it.angle * kotlin.math.PI / 360); listOf(CalcResult("扭转长度", l, "mm"), CalcResult("切口位置", it.width / 2, "mm")) }, ModelType.HORIZONTAL))
        _elbows.add(ElbowSpec(22, "爬坡扭弯", ElbowCategory.SPECIAL_SHAPE, "边爬坡边扭转", listOf(DefaultParams.width, DefaultParams.height, DefaultParams.angle, DefaultParams.distance), listOf("底边X", "斜边L", "扭转长度"), "复合计算", { val x = FormulaEngine.calcBottomX(it.distance, it.angle); val l = FormulaEngine.calcHypotenuse(it.distance, it.angle); val t = it.width * kotlin.math.tan(it.angle * kotlin.math.PI / 360); listOf(CalcResult("底边X", x, "mm"), CalcResult("斜边L", l, "mm"), CalcResult("扭转长度", t, "mm")) }, ModelType.RAMP))
        _elbows.add(ElbowSpec(23, "水平异形弯", ElbowCategory.SPECIAL_SHAPE, "非标准角度的水平转向", listOf(DefaultParams.width, DefaultParams.height, DefaultParams.angle, DefaultParams.distance), listOf("底边X", "斜边L", "切口宽"), "万能公式", { FormulaEngine.calcHorizontal(it) }, ModelType.HORIZONTAL))
        _elbows.add(ElbowSpec(24, "水平圆弧三通", ElbowCategory.SPECIAL_SHAPE, "带圆弧形分支的三通", listOf(DefaultParams.width, DefaultParams.height, DefaultParams.branchPos), listOf("主管切口", "支管直径", "圆弧半径"), "R = W/4", { listOf(CalcResult("主管切口", it.width * 0.4, "mm"), CalcResult("支管直径", it.width * 0.5, "mm"), CalcResult("圆弧半径", it.width / 4, "mm")) }, ModelType.TEE))
        _elbows.add(ElbowSpec(25, "垂直圆弧三通", ElbowCategory.SPECIAL_SHAPE, "带圆弧形分支的垂直三通", listOf(DefaultParams.width, DefaultParams.height, DefaultParams.branchPos), listOf("主管切口", "支管直径", "圆弧半径"), "R = W/4", { listOf(CalcResult("主管切口", it.width * 0.4, "mm"), CalcResult("支管直径", it.width * 0.5, "mm"), CalcResult("圆弧半径", it.width / 4, "mm")) }, ModelType.TEE))
        _elbows.add(ElbowSpec(26, "水平漏斗三通", ElbowCategory.SPECIAL_SHAPE, "带漏斗形过渡的三通", listOf(DefaultParams.width, DefaultParams.height, DefaultParams.branchPos), listOf("漏斗宽度", "漏斗高度", "切口宽"), "", { val f = it.width * 1.5; listOf(CalcResult("漏斗宽度", f, "mm"), CalcResult("漏斗高度", it.height * 0.5, "mm"), CalcResult("切口宽", f * 0.3, "mm")) }, ModelType.TEE))
        _elbows.add(ElbowSpec(27, "垂直漏斗三通", ElbowCategory.SPECIAL_SHAPE, "带漏斗形过渡的垂直三通", listOf(DefaultParams.width, DefaultParams.height, DefaultParams.branchPos), listOf("漏斗宽度", "漏斗高度", "切口宽"), "", { val f = it.width * 1.5; listOf(CalcResult("漏斗宽度", f, "mm"), CalcResult("漏斗高度", it.height * 0.5, "mm"), CalcResult("切口宽", f * 0.3, "mm")) }, ModelType.TEE))
        _elbows.add(ElbowSpec(28, "垂直异形弯", ElbowCategory.SPECIAL_SHAPE, "非标准角度的垂直转向", listOf(DefaultParams.width, DefaultParams.height, DefaultParams.angle, DefaultParams.distance), listOf("底边X", "斜边L", "垂直高度"), "万能公式", { FormulaEngine.calcRamp(it) }, ModelType.RAMP))
        _elbows.add(ElbowSpec(29, "扭曲弯头", ElbowCategory.SPECIAL_SHAPE, "复杂空间扭曲的弯头", listOf(DefaultParams.width, DefaultParams.height, ParamDef("扭曲角度", "angle", "°", 45.0, 1.0, 90.0), ParamDef("扭曲长度", "distance", "mm", 300.0, 100.0, 1000.0)), listOf("扭曲长度", "切口宽"), "L = b × tan(α/2)", { val l = it.distance * kotlin.math.tan(it.angle * kotlin.math.PI / 360); listOf(CalcResult("扭曲长度", l, "mm"), CalcResult("切口宽", l * 0.3, "mm")) }, ModelType.CUSTOM))
        
        // 5. 变径类 (8种)
        _elbows.add(ElbowSpec(30, "水平变宽", ElbowCategory.REDUCING, "水平方向改变宽度", listOf(DefaultParams.beforeWidth, DefaultParams.afterWidth, DefaultParams.height), listOf("宽度差", "斜边L", "切口宽"), "L = √(Δw² + H²)", { FormulaEngine.calcReducing(it.copy(beforeHeight = it.height, afterHeight = it.height)) }, ModelType.REDUCING))
        _elbows.add(ElbowSpec(31, "水平变高", ElbowCategory.REDUCING, "水平方向改变高度", listOf(DefaultParams.width, DefaultParams.beforeHeight, DefaultParams.afterHeight), listOf("高度差", "斜边L", "切口宽"), "L = √(Δh² + W²)", { val dh = kotlin.math.abs(it.afterHeight - it.beforeHeight); val l = kotlin.math.sqrt(dh * dh + it.width * it.width); listOf(CalcResult("高度差", dh, "mm"), CalcResult("斜边L", l, "mm"), CalcResult("切口宽", l * 0.3, "mm")) }, ModelType.REDUCING))
        _elbows.add(ElbowSpec(32, "水平变宽变高", ElbowCategory.REDUCING, "同时改变宽度和高度", listOf(DefaultParams.beforeWidth, DefaultParams.beforeHeight, DefaultParams.afterWidth, DefaultParams.afterHeight), listOf("宽度差", "高度差", "斜边L", "切口宽"), "L = √(Δw² + Δh²)", { val dw = kotlin.math.abs(it.afterWidth - it.beforeWidth); val dh = kotlin.math.abs(it.afterHeight - it.beforeHeight); val l = kotlin.math.sqrt(dw * dw + dh * dh); listOf(CalcResult("宽度差", dw, "mm"), CalcResult("高度差", dh, "mm"), CalcResult("斜边L", l, "mm"), CalcResult("切口宽", l * 0.3, "mm")) }, ModelType.REDUCING))
        _elbows.add(ElbowSpec(33, "爬坡变宽", ElbowCategory.REDUCING, "爬坡时改变宽度", listOf(DefaultParams.beforeWidth, DefaultParams.afterWidth, DefaultParams.height, DefaultParams.angle, DefaultParams.distance), listOf("宽度差", "斜边L", "爬坡高度"), "复合计算", { val dw = kotlin.math.abs(it.afterWidth - it.beforeWidth); val l = FormulaEngine.calcHypotenuse(it.distance, it.angle); val h = FormulaEngine.calcHeight(it.distance, it.angle); listOf(CalcResult("宽度差", dw, "mm"), CalcResult("斜边L", l, "mm"), CalcResult("爬坡高度", h, "mm")) }, ModelType.REDUCING))
        _elbows.add(ElbowSpec(34, "爬坡变高", ElbowCategory.REDUCING, "爬坡时改变高度", listOf(DefaultParams.width, DefaultParams.beforeHeight, DefaultParams.afterHeight, DefaultParams.angle, DefaultParams.distance), listOf("高度差", "斜边L", "爬坡高度"), "复合计算", { val dh = kotlin.math.abs(it.afterHeight - it.beforeHeight); val l = FormulaEngine.calcHypotenuse(it.distance, it.angle); val h = FormulaEngine.calcHeight(it.distance, it.angle); listOf(CalcResult("高度差", dh, "mm"), CalcResult("斜边L", l, "mm"), CalcResult("爬坡高度", h, "mm")) }, ModelType.REDUCING))
        _elbows.add(ElbowSpec(35, "爬坡变宽变高", ElbowCategory.REDUCING, "爬坡时同时改变宽高", listOf(DefaultParams.beforeWidth, DefaultParams.beforeHeight, DefaultParams.afterWidth, DefaultParams.afterHeight, DefaultParams.angle, DefaultParams.distance), listOf("宽度差", "高度差", "斜边L", "爬坡高度"), "复合计算", { val dw = kotlin.math.abs(it.afterWidth - it.beforeWidth); val dh = kotlin.math.abs(it.afterHeight - it.beforeHeight); val l = FormulaEngine.calcHypotenuse(it.distance, it.angle); val h = FormulaEngine.calcHeight(it.distance, it.angle); listOf(CalcResult("宽度差", dw, "mm"), CalcResult("高度差", dh, "mm"), CalcResult("斜边L", l, "mm"), CalcResult("爬坡高度", h, "mm")) }, ModelType.REDUCING))
        _elbows.add(ElbowSpec(36, "垂直变宽", ElbowCategory.REDUCING, "垂直方向改变宽度", listOf(DefaultParams.beforeWidth, DefaultParams.afterWidth, DefaultParams.height), listOf("宽度差", "斜边L", "切口宽"), "L = √(Δw² + H²)", { val dw = kotlin.math.abs(it.afterWidth - it.beforeWidth); val l = kotlin.math.sqrt(dw * dw + it.height * it.height); listOf(CalcResult("宽度差", dw, "mm"), CalcResult("斜边L", l, "mm"), CalcResult("切口宽", l * 0.3, "mm")) }, ModelType.REDUCING))
        _elbows.add(ElbowSpec(37, "垂直变高", ElbowCategory.REDUCING, "垂直方向改变高度", listOf(DefaultParams.width, DefaultParams.beforeHeight, DefaultParams.afterHeight), listOf("高度差", "垂直高度", "切口宽"), "直接计算", { val dh = kotlin.math.abs(it.afterHeight - it.beforeHeight); listOf(CalcResult("高度差", dh, "mm"), CalcResult("垂直高度", dh, "mm"), CalcResult("切口宽", dh * 0.3, "mm")) }, ModelType.REDUCING))
        
        // 6. 三通/四通类 (10种)
        _elbows.add(ElbowSpec(38, "水平等高左三通", ElbowCategory.TEE_CROSS, "水平方向左侧分支", listOf(DefaultParams.width, DefaultParams.height, DefaultParams.branchPos), listOf("主管切口", "支管宽度", "漏斗宽度"), "漏斗 = 1.5 × 支管宽", { FormulaEngine.calcTee(it) }, ModelType.TEE))
        _elbows.add(ElbowSpec(39, "水平等高右三通", ElbowCategory.TEE_CROSS, "水平方向右侧分支", listOf(DefaultParams.width, DefaultParams.height, DefaultParams.branchPos), listOf("主管切口", "支管宽度", "漏斗宽度"), "漏斗 = 1.5 × 支管宽", { FormulaEngine.calcTee(it) }, ModelType.TEE))
        _elbows.add(ElbowSpec(40, "水平等高正中三通", ElbowCategory.TEE_CROSS, "水平方向正中分支", listOf(DefaultParams.width, DefaultParams.height), listOf("主管切口", "支管宽度", "漏斗宽度"), "漏斗 = 1.5 × 支管宽", { listOf(CalcResult("主管切口", it.width * 0.4, "mm"), CalcResult("支管宽度", it.width * 0.5, "mm"), CalcResult("漏斗宽度", it.width * 0.75, "mm")) }, ModelType.TEE))
        _elbows.add(ElbowSpec(41, "水平变高左三通", ElbowCategory.TEE_CROSS, "左侧分支、主管变高", listOf(DefaultParams.width, DefaultParams.beforeHeight, DefaultParams.afterHeight, DefaultParams.branchPos), listOf("主管切口", "支管宽度", "漏斗宽度", "漏斗高度"), "变高计算", { val dh = kotlin.math.abs(it.afterHeight - it.beforeHeight); listOf(CalcResult("主管切口", it.width * 0.4, "mm"), CalcResult("支管宽度", it.width * 0.5, "mm"), CalcResult("漏斗宽度", it.width * 0.75, "mm"), CalcResult("漏斗高度", dh * 0.5, "mm")) }, ModelType.TEE))
        _elbows.add(ElbowSpec(42, "水平变高右三通", ElbowCategory.TEE_CROSS, "右侧分支、主管变高", listOf(DefaultParams.width, DefaultParams.beforeHeight, DefaultParams.afterHeight, DefaultParams.branchPos), listOf("主管切口", "支管宽度", "漏斗宽度", "漏斗高度"), "变高计算", { val dh = kotlin.math.abs(it.afterHeight - it.beforeHeight); listOf(CalcResult("主管切口", it.width * 0.4, "mm"), CalcResult("支管宽度", it.width * 0.5, "mm"), CalcResult("漏斗宽度", it.width * 0.75, "mm"), CalcResult("漏斗高度", dh * 0.5, "mm")) }, ModelType.TEE))
        _elbows.add(ElbowSpec(43, "垂直上三通", ElbowCategory.TEE_CROSS, "垂直方向上方分支", listOf(DefaultParams.width, DefaultParams.height), listOf("主管切口", "支管宽度", "漏斗宽度"), "漏斗 = 1.5 × 支管宽", { listOf(CalcResult("主管切口", it.width * 0.4, "mm"), CalcResult("支管宽度", it.width * 0.5, "mm"), CalcResult("漏斗宽度", it.width * 0.75, "mm")) }, ModelType.TEE))
        _elbows.add(ElbowSpec(44, "垂直下三通", ElbowCategory.TEE_CROSS, "垂直方向下方分支", listOf(DefaultParams.width, DefaultParams.height), listOf("主管切口", "支管宽度", "漏斗宽度"), "漏斗 = 1.5 × 支管宽", { listOf(CalcResult("主管切口", it.width * 0.4, "mm"), CalcResult("支管宽度", it.width * 0.5, "mm"), CalcResult("漏斗宽度", it.width * 0.75, "mm")) }, ModelType.TEE))
        _elbows.add(ElbowSpec(45, "水平十字四通", ElbowCategory.TEE_CROSS, "水平方向十字交叉", listOf(DefaultParams.width, DefaultParams.height), listOf("主管切口", "支管宽度", "漏斗宽度"), "四通 = 2 × 三通", { FormulaEngine.calcTee(it) + CalcResult("侧支管宽度", it.width * 0.4, "mm") }, ModelType.TEE))
        _elbows.add(ElbowSpec(46, "垂直十字四通", ElbowCategory.TEE_CROSS, "垂直方向十字交叉", listOf(DefaultParams.width, DefaultParams.height), listOf("主管切口", "支管宽度", "漏斗宽度"), "四通 = 2 × 三通", { listOf(CalcResult("主管切口", it.width * 0.4, "mm"), CalcResult("支管宽度", it.width * 0.5, "mm"), CalcResult("漏斗宽度", it.width * 0.75, "mm")) }, ModelType.TEE))
        _elbows.add(ElbowSpec(47, "爬坡三通", ElbowCategory.TEE_CROSS, "爬坡方向带分支", listOf(DefaultParams.width, DefaultParams.height, DefaultParams.angle, DefaultParams.distance, DefaultParams.branchPos), listOf("主管切口", "斜边L", "支管宽度", "爬坡高度"), "复合计算", { val l = FormulaEngine.calcHypotenuse(it.distance, it.angle); val h = FormulaEngine.calcHeight(it.distance, it.angle); listOf(CalcResult("主管切口", it.width * 0.4, "mm"), CalcResult("斜边L", l, "mm"), CalcResult("支管宽度", it.width * 0.5, "mm"), CalcResult("爬坡高度", h, "mm")) }, ModelType.TEE))
        
        // 7. 折角类 (5种)
        _elbows.add(ElbowSpec(48, "水平折角", ElbowCategory.FOLDED_ANGLE, "水平方向的折角弯头", listOf(DefaultParams.width, DefaultParams.height, DefaultParams.angle, DefaultParams.distance), listOf("折角X", "切口宽", "折弯位置"), "X = b × tan(α/2)", { val x = FormulaEngine.calcBottomX(it.distance, it.angle); listOf(CalcResult("折角X", x, "mm"), CalcResult("切口宽", x * 0.3, "mm"), CalcResult("折弯位置", it.width / 2 - x / 2, "mm")) }, ModelType.FOLDED))
        _elbows.add(ElbowSpec(49, "爬坡折角", ElbowCategory.FOLDED_ANGLE, "爬坡方向的折角弯头", listOf(DefaultParams.width, DefaultParams.height, DefaultParams.angle, DefaultParams.distance), listOf("折角X", "斜边L", "爬坡高度", "折弯位置"), "复合计算", { val x = FormulaEngine.calcBottomX(it.distance, it.angle); val l = FormulaEngine.calcHypotenuse(it.distance, it.angle); val h = FormulaEngine.calcHeight(it.distance, it.angle); listOf(CalcResult("折角X", x, "mm"), CalcResult("斜边L", l, "mm"), CalcResult("爬坡高度", h, "mm"), CalcResult("折弯位置", it.width / 2 - x / 2, "mm")) }, ModelType.FOLDED))
        _elbows.add(ElbowSpec(50, "垂直折角", ElbowCategory.FOLDED_ANGLE, "垂直方向的折角弯头", listOf(DefaultParams.width, DefaultParams.height, DefaultParams.heightOffset), listOf("折角X", "垂直高度", "折弯位置"), "直接计算", { listOf(CalcResult("折角X", it.width / 2, "mm"), CalcResult("垂直高度", it.heightOffset, "mm"), CalcResult("折弯位置", it.width / 4, "mm")) }, ModelType.FOLDED))
        _elbows.add(ElbowSpec(51, "折角盖板弯", ElbowCategory.FOLDED_ANGLE, "带盖板的折角弯头", listOf(DefaultParams.width, DefaultParams.height, DefaultParams.angle, DefaultParams.distance), listOf("折角X", "盖板宽度", "盖板长度"), "盖板 = 1.2 × 主体", { val x = FormulaEngine.calcBottomX(it.distance, it.angle); listOf(CalcResult("折角X", x, "mm"), CalcResult("盖板宽度", it.width * 1.1, "mm"), CalcResult("盖板长度", x * 1.2, "mm")) }, ModelType.FOLDED))
        _elbows.add(ElbowSpec(52, "水平折角盖板", ElbowCategory.FOLDED_ANGLE, "水平折角专用盖板", listOf(DefaultParams.width, DefaultParams.height, DefaultParams.angle, DefaultParams.distance), listOf("盖板宽度", "盖板长度"), "盖板 = 1.2 × 主体", { val x = FormulaEngine.calcBottomX(it.distance, it.angle); listOf(CalcResult("盖板宽度", it.width * 1.1, "mm"), CalcResult("盖板长度", x * 1.2, "mm")) }, ModelType.FOLDED))
        
        // 8. 任意角类 (16种)
        _elbows.add(ElbowSpec(53, "任意角左爬坡", ElbowCategory.CUSTOM_ANGLE, "支持0-180度任意角度", listOf(DefaultParams.width, DefaultParams.height, DefaultParams.angle, DefaultParams.distance), listOf("底边X", "斜边L", "爬坡高度", "切口宽", "折弯位置"), "万能公式: X = b × tan(α/2)", { FormulaEngine.calcCustomAngle(it) }, ModelType.CUSTOM))
        _elbows.add(ElbowSpec(54, "任意角右爬坡", ElbowCategory.CUSTOM_ANGLE, "支持0-180度任意角度", listOf(DefaultParams.width, DefaultParams.height, DefaultParams.angle, DefaultParams.distance), listOf("底边X", "斜边L", "爬坡高度", "切口宽", "折弯位置"), "万能公式: X = b × tan(α/2)", { FormulaEngine.calcCustomAngle(it) }, ModelType.CUSTOM))
        _elbows.add(ElbowSpec(55, "任意角水平左弯", ElbowCategory.CUSTOM_ANGLE, "支持0-180度任意角度", listOf(DefaultParams.width, DefaultParams.height, DefaultParams.angle, DefaultParams.distance), listOf("底边X", "弧长L", "切口宽"), "万能公式", { FormulaEngine.calcHorizontal(it) }, ModelType.CUSTOM))
        _elbows.add(ElbowSpec(56, "任意角水平右弯", ElbowCategory.CUSTOM_ANGLE, "支持0-180度任意角度", listOf(DefaultParams.width, DefaultParams.height, DefaultParams.angle, DefaultParams.distance), listOf("底边X", "弧长L", "切口宽"), "万能公式", { FormulaEngine.calcHorizontal(it) }, ModelType.CUSTOM))
        _elbows.add(ElbowSpec(57, "任意角左上翻", ElbowCategory.CUSTOM_ANGLE, "支持0-180度任意角度", listOf(DefaultParams.width, DefaultParams.height, DefaultParams.angle, DefaultParams.distance, DefaultParams.heightOffset), listOf("底边X", "斜边L", "翻起高度", "切口宽"), "万能公式", { FormulaEngine.calcCustomAngle(it) }, ModelType.CUSTOM))
        _elbows.add(ElbowSpec(58, "任意角右上翻", ElbowCategory.CUSTOM_ANGLE, "支持0-180度任意角度", listOf(DefaultParams.width, DefaultParams.height, DefaultParams.angle, DefaultParams.distance, DefaultParams.heightOffset), listOf("底边X", "斜边L", "翻起高度", "切口宽"), "万能公式", { FormulaEngine.calcCustomAngle(it) }, ModelType.CUSTOM))
        _elbows.add(ElbowSpec(59, "任意角左下翻", ElbowCategory.CUSTOM_ANGLE, "支持0-180度任意角度", listOf(DefaultParams.width, DefaultParams.height, DefaultParams.angle, DefaultParams.distance, DefaultParams.heightOffset), listOf("底边X", "斜边L", "翻下高度", "切口宽"), "万能公式", { FormulaEngine.calcCustomAngle(it) }, ModelType.CUSTOM))
        _elbows.add(ElbowSpec(60, "任意角右下翻", ElbowCategory.CUSTOM_ANGLE, "支持0-180度任意角度", listOf(DefaultParams.width, DefaultParams.height, DefaultParams.angle, DefaultParams.distance, DefaultParams.heightOffset), listOf("底边X", "斜边L", "翻下高度", "切口宽"), "万能公式", { FormulaEngine.calcCustomAngle(it) }, ModelType.CUSTOM))
        _elbows.add(ElbowSpec(61, "任意角垂直上弯", ElbowCategory.CUSTOM_ANGLE, "支持0-90度任意角度", listOf(DefaultParams.width, DefaultParams.height, ParamDef("弯头角度", "angle", "°", 90.0, 1.0, 90.0), DefaultParams.distance), listOf("垂直高度", "斜边L", "切口宽"), "h = b × tan(α)", { val h = FormulaEngine.calcHeight(it.distance, it.angle); val l = FormulaEngine.calcHypotenuse(it.distance, it.angle); listOf(CalcResult("垂直高度", h, "mm"), CalcResult("斜边L", l, "mm"), CalcResult("切口宽", l * 0.3, "mm")) }, ModelType.CUSTOM))
        _elbows.add(ElbowSpec(62, "任意角垂直下弯", ElbowCategory.CUSTOM_ANGLE, "支持0-90度任意角度", listOf(DefaultParams.width, DefaultParams.height, ParamDef("弯头角度", "angle", "°", 90.0, 1.0, 90.0), DefaultParams.distance), listOf("下降高度", "斜边L", "切口宽"), "h = b × tan(α)", { val h = FormulaEngine.calcHeight(it.distance, it.angle); val l = FormulaEngine.calcHypotenuse(it.distance, it.angle); listOf(CalcResult("下降高度", h, "mm"), CalcResult("斜边L", l, "mm"), CalcResult("切口宽", l * 0.3, "mm")) }, ModelType.CUSTOM))
        _elbows.add(ElbowSpec(63, "任意角多层爬坡", ElbowCategory.CUSTOM_ANGLE, "支持多层的任意角爬坡", listOf(DefaultParams.width, DefaultParams.height, DefaultParams.angle, DefaultParams.distance, DefaultParams.layers, DefaultParams.layerSpacing), listOf("底边X", "斜边L", "层偏移e", "总宽度c", "总高度h"), "多层偏移公式", { val x = FormulaEngine.calcBottomX(it.distance, it.angle); val l = FormulaEngine.calcHypotenuse(it.distance, it.angle); val offsets = FormulaEngine.calcMultiLayerOffset(it.layerSpacing, it.distance, it.angle); listOf(CalcResult("底边X", x, "mm"), CalcResult("斜边L", l, "mm"), CalcResult("层偏移e", offsets[0], "mm"), CalcResult("总宽度c", offsets[1], "mm"), CalcResult("总高度h", offsets[2], "mm")) }, ModelType.CUSTOM))
        _elbows.add(ElbowSpec(64, "任意角多层水平", ElbowCategory.CUSTOM_ANGLE, "支持多层的任意角水平弯", listOf(DefaultParams.width, DefaultParams.height, DefaultParams.angle, DefaultParams.distance, DefaultParams.layers, DefaultParams.layerSpacing), listOf("底边X", "斜边L", "层偏移e", "总宽度c"), "多层偏移公式", { val x = FormulaEngine.calcBottomX(it.distance, it.angle); val l = FormulaEngine.calcHypotenuse(it.distance, it.angle); val offsets = FormulaEngine.calcMultiLayerOffset(it.layerSpacing, it.distance, it.angle); listOf(CalcResult("底边X", x, "mm"), CalcResult("斜边L", l, "mm"), CalcResult("层偏移e", offsets[0], "mm"), CalcResult("总宽度c", offsets[1], "mm")) }, ModelType.CUSTOM))
        _elbows.add(ElbowSpec(65, "任意角折角", ElbowCategory.CUSTOM_ANGLE, "支持任意角度的折角", listOf(DefaultParams.width, DefaultParams.height, DefaultParams.angle, DefaultParams.distance), listOf("折角X", "切口宽", "折弯位置"), "万能公式", { val x = FormulaEngine.calcBottomX(it.distance, it.angle); listOf(CalcResult("折角X", x, "mm"), CalcResult("切口宽", x * 0.3, "mm"), CalcResult("折弯位置", it.width / 2 - x / 2, "mm")) }, ModelType.CUSTOM))
        _elbows.add(ElbowSpec(66, "任意角三通", ElbowCategory.CUSTOM_ANGLE, "支持任意角度的三通", listOf(DefaultParams.width, DefaultParams.height, DefaultParams.branchPos), listOf("主管切口", "支管宽度", "漏斗宽度"), "标准三通计算", { FormulaEngine.calcTee(it) }, ModelType.CUSTOM))
        _elbows.add(ElbowSpec(67, "任意角变径", ElbowCategory.CUSTOM_ANGLE, "支持任意角度的变径", listOf(DefaultParams.beforeWidth, DefaultParams.beforeHeight, DefaultParams.afterWidth, DefaultParams.afterHeight), listOf("宽度差", "高度差", "斜边L", "切口宽"), "变径公式", { FormulaEngine.calcReducing(it) }, ModelType.CUSTOM))
        _elbows.add(ElbowSpec(68, "万能公式计算器", ElbowCategory.CUSTOM_ANGLE, "通用万能公式计算器", listOf(DefaultParams.width, DefaultParams.height, DefaultParams.angle, DefaultParams.distance, DefaultParams.layers, DefaultParams.layerSpacing), listOf("底边X", "斜边L", "垂直高度", "切口宽", "多层偏移"), "万能公式: X = b×tan(α/2), L = b/sin(α), h = b×tan(α)", { val x = FormulaEngine.calcBottomX(it.distance, it.angle); val l = FormulaEngine.calcHypotenuse(it.distance, it.angle); val h = FormulaEngine.calcHeight(it.distance, it.angle); val cut = FormulaEngine.calcCutWidth(it.height, it.angle); val offset = it.layerSpacing + it.distance * kotlin.math.tan(it.angle * kotlin.math.PI / 360); listOf(CalcResult("底边X", x, "mm", "X = b × tan(α/2)"), CalcResult("斜边L", l, "mm", "L = b / sin(α)"), CalcResult("垂直高度", h, "mm", "h = b × tan(α)"), CalcResult("切口宽", cut, "mm"), CalcResult("层偏移", offset, "mm", "e = d + b×tan(α/2)")) }, ModelType.CUSTOM))
    }
    
    fun getById(id: Int): ElbowSpec? = _elbows.find { it.id == id }
    fun getByCategory(category: ElbowCategory): List<ElbowSpec> = _elbows.filter { it.category == category }
    fun search(keyword: String): List<ElbowSpec> {
        if (keyword.isBlank()) return _elbows
        return _elbows.filter { it.name.contains(keyword, true) || it.description.contains(keyword, true) || it.category.displayName.contains(keyword, true) }
    }
    fun getCategoryStats(): Map<ElbowCategory, Int> = _elbows.groupBy { it.category }.mapValues { it.value.size }
}
